### ISSUE TITLE
SyntaxError: Unexpected identifier (line 94, file "Code.gs")

### ISSUE THREAD

**Issue by e-orlov** [aliciawilliams/analyzingtext#3]
[nlcall.gs](https://github.com/aliciawilliams/analyzingtext/blob/master/nlcall.gs) can't be saved as script: `error SyntaxError: Unexpected identifier (line 94, file "Code.gs")`

**Comment by BenC202** [comment]
I'm getting the same error. @aliciawilliams are you able to help at all? Thanks in advance! :)

**Comment by aliciawilliams** [comment]
@e-orlov @BenC202 Thank you for your note - my code in this repo isn't updated for the V8 transition for Apps Script. Will you try the version over in the Google Workspace org? https://github.com/googleworkspace/solutions/tree/master/feedback-sentiment-analysis

It's very similar, but doesn't use the Form or trigger that this solution uses. I'll try to get this one updated in the future.

**Comment by BenC202** [comment]
Thank you so much for taking the time to reply - that's working perfectly!
